slogan: "Thanks to Lucas' mama"

theme: cerulean
inverse: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "My Github"
    url: http://www.github.com/pnyiu
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: https://www.linkedin.com/in/pnyiu/
    intro: "My Linkin account."
    icon: "fa fa-linkedin"

widgets:
#- search
#- recent_comments
- category
- tagcloud
- recent_posts
- links

rss:
fancybox: true
favicon: "favicon/favicon.png"
duoshuo_shortname: #freemindtheme

# Analytics
google_analytics:
  enable: true
  siteid: UA-103782633-2
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: false
jiathis: false

# built-in comment system
#comment_js:
#  type: "github"
#  user: "wzpan"
#  repo: "hexo-theme-freemind-blog"
#  client_id: "bf7d4ba11877db88543e"
#  client_secret: "bff8a6b06b745c0bfcdccbe225623ea8e2a057bb"
#  count: 5
